tesseract:
  path: 'G:\FYP\Tesseract-OCR\tesseract.exe'

text_detection:
  confidence_threshold: 0.70
  nms_threshold: 0.8

data:
  templates:
    path: 'G:\FYP\imgflip-scrapper\data\templates\'
